server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-app
          __path__: /backend/logs/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<prefix>\S+) \[(?P<level>\S+)\] (?P<message>.*)$'
      - labels:
          timestamp: timestamp
          prefix: prefix
          level: level
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
