name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: cd ./backend && go mod download

      - name: Deployment
        env:
          MONGO_URI: mongodb://localhost:27017
          DB_NAME: swiftcodes
          LOAD_INITIAL_DATA: true
          SWIFT_DATA_FILE: ./configs/default-data.csv
          VERSION: v1
          DEBUG: false
        run: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh

